name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.0 - 3.10.0"
          cache: "poetry"
